# Generated by Django 5.1.6 on 2025-02-19 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Rozrusznik', 'Rozrusznik'), ('Alternator', 'Alternator')], max_length=15)),
                ('car_name', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_engine', models.CharField(max_length=255)),
                ('car_vin', models.CharField(max_length=17)),
                ('item_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Nowy', 'Nowy'), ('Zlecenie przyjęte', 'Zlecenie przyjęte'), ('W realizacji', 'W realizacji'), ('Ukończone zlecenie', 'Ukończone zlecenie')], default='Nowy', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
